coverage:
  status:
    project:
      default:
        enabled: yes
        target: 40%
    patch:
      default:
        enabled: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
