name: CI
on: [push, pull_request]
jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install requirements
        run: pip install -r ./requirements/quality.txt

      - name: Run tox
        run: tox

      - name: Run black formatter
        run: black --check .

      - name: Run isort
        run: isort --check-only --diff --recursive tests test_utils edx_sysadmin test_settings.py

      - name: Run pylint
        run: pylint edx_sysadmin tests test_utils

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
