name: CI
on: [push]
jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install quality equirements
        run: pip install -r ./requirements/quality.txt

      - name: Run black formatter
        run: black --check .

      - name: Setup edX
        run: |
          cd ..
          git clone https://github.com/edx/devstack.git
          cd devstack
          sed -i 's/:cached//g' ./docker-compose-host.yml
          make dev.clone.https
          cd ../edx-platform
          git remote add mitodl https://github.com/mitodl/edx-platform.git
          git fetch mitodl
          git checkout mitodl/arslan/fix-pipeline-import

      - name: Run tests
        run: |
          cd ../devstack
          DEVSTACK_WORKSPACE=$PWD/.. docker-compose -f docker-compose.yml -f docker-compose-host.yml run -v $PWD/../edx-sysadmin:/edx-sysadmin lms /edx-sysadmin/run_devstack_integration_tests.sh

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
